package-lock.json, package/src/index.ts, package/src/pattern/constants.ts, package/src/pattern/index.ts, package/src/pattern/pattern.test.ts, package/src/pattern/pattern.ts
=> feat(UIKIT-734): Реализован pattern

README.md, package/src/index.ts, package/src/ogrnIP/constants.ts, package/src/ogrnIP/index.ts, package/src/ogrnIP/ogrnIP.test.ts, package/src/ogrnIP/ogrnIP.ts, package/src/ogrnUL/constants.ts, package/src/ogrnUL/index.ts, package/src/ogrnUL/ogrnUL.test.ts, package/src/ogrnUL/ogrnUL.ts
=> feat(UIKIT-733): Реализован ogrnUl и ogrnIP

README.md, package/src/any/any.test.ts, package/src/any/any.ts, package/src/any/index.ts, package/src/index.ts, package/src/when/index.ts, package/src/when/when.test.ts, package/src/when/when.ts
=> feat(UIKIT-688): Реализован any и when

package/src/date/index.ts, package/src/index.ts
=> wip(UIKIT-691): Добавлены экспорты для date

README.md, package-lock.json, package/src/index.ts, package/src/integer/constants.ts, package/src/integer/index.ts, package/src/integer/integer.test.ts, package/src/integer/integer.ts
=> feat(UIKIT-760): Реализован integer

README.md, package/src/index.ts, package/src/positiveNumber/constants.ts, package/src/positiveNumber/index.ts, package/src/positiveNumber/positiveNumber.test.ts, package/src/positiveNumber/positiveNumber.ts
=> feat(UIKIT-761): Реализован positiveNumber

README.md, package/src/index.ts, package/src/toPrettyError/index.ts, package/src/toPrettyError/toPrettyError.test.ts, package/src/toPrettyError/toPrettyError.ts
=> feat(UIKIT-765): Реалиован toPrettyError

README.md, package/src/index.ts, package/src/object/object.ts, react-hook-form-resolver/README.md, react-hook-form-resolver/src/resolver/resolver.ts
=> feat(UIKIT-814): Реализован type ObjectGuard

package-lock.json, package/src/max/max.ts, package/src/min/min.ts
=> bug(UIKIT-826): Изменено дефолтное сообщение ошибки для min и max

package/src/core/utils/index.ts, package/src/core/utils/isNoDoubleZeroStart/index.ts, package/src/core/utils/isNoDoubleZeroStart/isNoDoubleZeroStart.test.ts, package/src/core/utils/isNoDoubleZeroStart/isNoDoubleZeroStart.ts, package/src/innIP/innIP.test.ts, package/src/innIP/innIP.ts, package/src/innUL/innUL.test.ts, package/src/innUL/innUL.ts
=> feat(UIKIT-818): Доработаны правила валидации ИНН

package-lock.json, package/src/index.ts, package/src/kpp/constants.ts, package/src/kpp/kpp.test.ts, package/src/kpp/kpp.ts
=> feat(UIKIT-819): Доработано правило для КПП

README.md, package/src/guid/constants.ts, package/src/guid/guid.test.ts, package/src/guid/guid.ts, package/src/guid/index.ts, package/src/index.ts
=> feat(UIKIT-881): Реализовано правило валидации для GUID

README.md, package/src/core/compose/compose.ts, package/src/core/rule/callRule/callRule.test.ts, package/src/core/rule/callRule/callRule.ts, package/src/core/rule/callRule/index.ts, package/src/core/rule/index.ts, package/src/core/rule/types.ts, package/src/object/object.test.ts, package/src/object/object.ts, package/src/or/or.ts, package/src/when/when.test.ts, package/src/when/when.ts
=> feat(UIKIT-823): Добавлена возможность возвращать rule из кастомного rule

package/src/max/max.ts, package/src/min/min.ts
=> bug(UIKIT-895): Исправлена ошибка потери типизация ctx при композиции правил

README.md, package/src/index.ts, package/src/optional/optionalAsync/index.ts, package/src/optional/optionalAsync/optionalAsync.test.ts, package/src/optional/optionalAsync/optionalAsync.ts
=> bug(UIKIT-921): Добавлен optionalAsync

README.md, package/.eslintrc, package/src/containsDifferentCases/constants.ts, package/src/containsDifferentCases/containsDifferentCases.test.ts, package/src/containsDifferentCases/containsDifferentCases.ts, package/src/containsDifferentCases/index.ts, package/src/containsNumbers/constants.ts, package/src/containsNumbers/containsNumbers.test.ts, package/src/containsNumbers/containsNumbers.ts, package/src/containsNumbers/index.ts, package/src/containsPunctuationMarks/constants.ts, package/src/containsPunctuationMarks/containsPunctuationMarks.test.ts, package/src/containsPunctuationMarks/containsPunctuationMarks.ts, package/src/containsPunctuationMarks/index.ts
=> feat(UIKIT-941): Добавлены новые методы валидации строк

package/src/index.ts
=> bug(UIKIT-953): Добавлены отсутствующие экспорты

package/src/core/guard/createGuard/createGuard.test.ts, package/src/core/guard/createGuard/createGuard.ts, package/src/object/object.test.ts
=> bug(UIKIT-956): Исправлен доступ к ctx.values с вложенными guard

README.md, package/src/minYearsOld/constants.ts, package/src/minYearsOld/index.ts, package/src/minYearsOld/minYearsOld.test.ts, package/src/minYearsOld/minYearsOld.ts
=> feat(UIKIT-776): Реализует правило minYearsOld

package/src/deepPartial/deepPartial.test.ts, package/src/index.ts, package/src/object/object.ts, package/src/object/objectAsync/objectAsync.ts, package/src/optional/optionalAsync/optionalAsync.ts
=> bug(UIKIT-976,validations): Исправлен баг не работающего asyncObject и object с rules

README.md, package/src/index.ts, package/src/length/constants.ts, package/src/length/index.ts, package/src/length/length.test.ts, package/src/length/length.ts
=> feat(UIKIT-907): Добавлено правило валидации length

package/src/array/array.test.ts, package/src/arrayItem/arrayItem.test.ts, package/src/boolean/boolean.test.ts, package/src/containsDifferentCases/containsDifferentCases.test.ts, package/src/containsNumbers/containsNumbers.test.ts, package/src/containsPunctuationMarks/containsPunctuationMarks.test.ts, package/src/core/rule/required/required.test.ts, package/src/date/date.test.ts, package/src/deepPartial/deepPartial.test.ts, package/src/email/email.test.ts, package/src/guid/guid.test.ts, package/src/innFL/innFL.test.ts, package/src/innIP/innIP.test.ts, package/src/innTwelveSymbols/innTwelveSymbols.test.ts, package/src/innUL/innUL.test.ts, package/src/integer/integer.test.ts, package/src/kpp/kpp.test.ts, package/src/mobilePhone/mobilePhone.test.ts, package/src/number/number.test.ts, package/src/ogrnIP/ogrnIP.test.ts, package/src/ogrnUL/ogrnUL.test.ts, package/src/onlyNumber/onlyNumber.test.ts, package/src/passportSeries/passportSeries.test.ts, package/src/pattern/pattern.test.ts, package/src/positiveNumber/positiveNumber.test.ts, package/src/snils/snils.test.ts
Внесены изменения в формат тест-кейсов, но основе правил нового [Astral Unit Testing Guide](https://industrious-search-cdf.notion.site/Astral-Frontend-Unit-Testing-Guide-71120289ed89424e912ebe7fa8b7e39b?pvs=4)
=> test: Часть тестов переформатированы в новый формат

package-lock.json, react-hook-form-resolver/package.json
=> bug(UIKIT-1167): Зафиксирована версия @hookform/resolvers

package/src/index.ts
=> bug(UIKIT-1292): Добавлен экспорт minYearsOld из пакета

package/src/email/constants.ts, package/src/email/email.test.ts, package/src/email/email.ts
=> bug(UIKIT-1508,email): Дополнены требования для email

package/src/innFL/constants.ts, package/src/innIP/constants.ts, package/src/innUL/constants.ts
=> bug(UIKIT-1680,Inn): Исправлено сообщение об ошибке
